/**
 * WorkspacePage — Espace de travail · Inbox IA
 * Action feed (devis, RDV, clients, factures, emails, tâches) generated by AI agents.
 * Wired to real data: GET /api/marketplace/work-items?limit=100
 */
import { useEffect, useMemo, useState } from 'react';
import {
  Search, Sparkles, Inbox, Clock, DollarSign, BadgeCheck,
  ArrowUpRight, ArrowDownRight, Minus, ChevronsUpDown, SlidersHorizontal,
  RefreshCw, CheckCircle2, Check, X, Archive, MoreVertical,
  FileText, Calendar, User, Receipt, Mail, Target, Edit3, Eye, Flame,
} from 'lucide-react';
import api from '@/services/api';
import { useCurrency } from '@/hooks/useCurrency';

const C = {
  greenDeep: '#0A4F3C', greenDark: '#063D2E', greenInk: '#042A1F',
  cream: '#FFFAF0', creamDeep: '#F5EDD6',
  gold: '#D4A017', goldDeep: '#B8860B', goldDark: '#8B6914', goldSoft: '#FEF3C7', goldLight: '#FCD34D',
  indigo: '#4338CA', indigoDeep: '#3730A3', indigoDark: '#1E1B4B', indigoSoft: '#E0E7FF', indigoLight: '#A5B4FC',
  terracotta: '#E07856', terraDeep: '#C25C3D', terraDark: '#8B3F26', terraSoft: '#FFEDE5',
  sage: '#86C5A0', sageDeep: '#5BA47C', sageDark: '#2D6A4F', sageSoft: '#D4F1DF',
  red: '#EF4444', redSoft: '#FEE2E2', redDeep: '#DC2626',
  blue: '#0EA5E9', blueSoft: '#E0F2FE', blueDeep: '#0284C7',
  cyan: '#06B6D4', cyanSoft: '#CFFAFE',
  purple: '#7C3AED', purpleSoft: '#F3E8FF', purpleDeep: '#5B21B6',
  ink: '#0A2A20', inkSoft: '#5A6B62', inkLight: '#94A3A0',
  onGreenSoft: '#A8C9B8',
} as const;

type TypeKey = 'devis' | 'rdv' | 'client' | 'facture' | 'email' | 'task';
type StatusKey = 'pending' | 'approved' | 'rejected' | 'completed';
type Priority = 'urgent' | 'high' | 'medium' | 'low';
type AgentKey = 'commercial' | 'reception' | 'rh' | 'cfo' | 'marketing' | 'workflow' | 'legal';

interface Action {
  id: string;
  type: TypeKey;
  title: string;
  sub: string;
  agent: AgentKey;
  date: string;
  rawDate: number; // ms epoch for sorting/grouping
  status: StatusKey;
  priority: Priority;
  client?: string;
  value?: number;
  duration?: string;
  unread?: boolean;
  raw: Record<string, unknown>;
}

interface RawWorkItem {
  id: string;
  type: string;
  title?: string;
  summary?: string;
  status?: string;
  agentName?: string;
  agentIcon?: string;
  data?: Record<string, unknown>;
  createdAt?: { _seconds?: number; seconds?: number } | string | number;
}

const TYPES: Record<TypeKey, { label: string; icon: typeof FileText; color: string; bg: string; deep: string }> = {
  devis:   { label: 'Devis',         icon: FileText, color: C.indigo,     bg: C.indigoSoft, deep: C.indigoDeep },
  rdv:     { label: 'Rendez-vous',   icon: Calendar, color: C.blue,       bg: C.blueSoft,   deep: C.blueDeep },
  client:  { label: 'Nouveau client', icon: User,    color: C.sage,       bg: C.sageSoft,   deep: C.sageDark },
  facture: { label: 'Facture',       icon: Receipt,  color: C.gold,       bg: C.goldSoft,   deep: C.goldDark },
  email:   { label: 'Email',         icon: Mail,     color: C.purple,     bg: C.purpleSoft, deep: C.purpleDeep },
  task:    { label: 'Tâche',         icon: Target,   color: C.terracotta, bg: C.terraSoft,  deep: C.terraDeep },
};

const AGENTS_INFO: Record<AgentKey, { name: string; emoji: string; color: string }> = {
  commercial: { name: 'Agent Commercial',  emoji: '💼', color: C.gold },
  reception:  { name: 'Agent Réception',   emoji: '📞', color: C.cyan },
  rh:         { name: 'Agent RH',          emoji: '👥', color: C.sage },
  cfo:        { name: 'Agent CFO',         emoji: '💰', color: C.gold },
  marketing:  { name: 'Agent Marketing',   emoji: '📣', color: C.terracotta },
  workflow:   { name: 'Agent Workflow',    emoji: '⚡', color: C.indigo },
  legal:      { name: 'Agent Légal',       emoji: '⚖️', color: C.purple },
};

const STATUS_CONFIG: Record<StatusKey, { label: string; color: string; bg: string; deep: string }> = {
  pending:   { label: 'En attente', color: C.gold,   bg: C.goldSoft,   deep: C.goldDark },
  approved:  { label: 'Approuvé',   color: C.sage,   bg: C.sageSoft,   deep: C.sageDark },
  rejected:  { label: 'Rejeté',     color: C.red,    bg: C.redSoft,    deep: C.redDeep },
  completed: { label: 'Complété',   color: C.indigo, bg: C.indigoSoft, deep: C.indigoDeep },
};

const PRIORITY_CONFIG: Record<Priority, { label: string; color: string; bg: string; icon: string }> = {
  urgent: { label: 'URGENT',  color: C.red,        bg: C.redSoft,    icon: '🔥' },
  high:   { label: 'HAUTE',   color: C.terraDeep,  bg: C.terraSoft,  icon: '⬆' },
  medium: { label: 'MOYENNE', color: C.goldDark,   bg: C.goldSoft,   icon: '●' },
  low:    { label: 'BASSE',   color: C.sageDark,   bg: C.sageSoft,   icon: '⬇' },
};

const TYPE_FROM_RAW: Record<string, TypeKey> = {
  appointment_created: 'rdv',
  meeting_scheduled: 'rdv',
  client_added: 'client',
  lead_added: 'client',
  quote_created: 'devis',
  invoice_created: 'facture',
  email_sent: 'email',
  email_drafted: 'email',
  newsletter_sent: 'email',
  alert_sent: 'task',
  report_generated: 'task',
  diagnostic_completed: 'task',
  security_check: 'task',
};

function mapType(raw: string): TypeKey {
  return TYPE_FROM_RAW[raw] ?? 'task';
}

function mapAgent(name?: string, fallbackType?: TypeKey): AgentKey {
  const n = (name || '').toLowerCase();
  if (n.includes('commerc')) return 'commercial';
  if (n.includes('récept') || n.includes('recept')) return 'reception';
  if (n.includes('rh') || n.includes('hr')) return 'rh';
  if (n.includes('cfo') || n.includes('compt') || n.includes('finance')) return 'cfo';
  if (n.includes('market')) return 'marketing';
  if (n.includes('legal') || n.includes('lég')) return 'legal';
  if (n.includes('flow')) return 'workflow';
  if (fallbackType === 'devis') return 'commercial';
  if (fallbackType === 'rdv' || fallbackType === 'client') return 'reception';
  if (fallbackType === 'facture') return 'cfo';
  if (fallbackType === 'email') return 'marketing';
  return 'workflow';
}

function mapStatus(s?: string): StatusKey {
  const v = (s || '').toLowerCase();
  if (v === 'approved' || v === 'accepted') return 'approved';
  if (v === 'rejected' || v === 'declined' || v === 'canceled' || v === 'cancelled') return 'rejected';
  if (v === 'completed' || v === 'sent' || v === 'paid' || v === 'done') return 'completed';
  return 'pending';
}

function derivePriority(type: TypeKey, value?: number, ageHours?: number): Priority {
  if (type === 'task' && (ageHours ?? 0) > 72) return 'urgent';
  if (typeof value === 'number') {
    if (value >= 5_000_000) return 'urgent';
    if (value >= 1_000_000) return 'high';
    if (value >= 250_000) return 'medium';
    return 'low';
  }
  return 'medium';
}

function tsToMs(t: RawWorkItem['createdAt']): number {
  if (!t) return Date.now();
  if (typeof t === 'number') return t < 1e12 ? t * 1000 : t;
  if (typeof t === 'string') { const d = Date.parse(t); return isNaN(d) ? Date.now() : d; }
  if (typeof t === 'object') {
    const s = (t as { _seconds?: number; seconds?: number })._seconds ?? (t as { seconds?: number }).seconds;
    return typeof s === 'number' ? s * 1000 : Date.now();
  }
  return Date.now();
}

function formatActionDate(ms: number): string {
  const d = new Date(ms);
  const today = new Date(); today.setHours(0, 0, 0, 0);
  const yest = new Date(today.getTime() - 86_400_000);
  const dayStart = new Date(d); dayStart.setHours(0, 0, 0, 0);
  const hh = String(d.getHours()).padStart(2, '0');
  const mm = String(d.getMinutes()).padStart(2, '0');
  if (dayStart.getTime() === today.getTime()) return `Aujourd'hui · ${hh}:${mm}`;
  if (dayStart.getTime() === yest.getTime()) return `Hier · ${hh}:${mm}`;
  const months = ['janv', 'févr', 'mars', 'avril', 'mai', 'juin', 'juil', 'août', 'sept', 'oct', 'nov', 'déc'];
  return `${d.getDate()} ${months[d.getMonth()]} · ${hh}:${mm}`;
}

function groupKey(ms: number): string {
  const d = new Date(ms);
  const today = new Date(); today.setHours(0, 0, 0, 0);
  const yest = new Date(today.getTime() - 86_400_000);
  const weekStart = new Date(today); weekStart.setDate(today.getDate() - today.getDay());
  const dayStart = new Date(d); dayStart.setHours(0, 0, 0, 0);
  if (dayStart.getTime() === today.getTime()) return "Aujourd'hui";
  if (dayStart.getTime() === yest.getTime()) return 'Hier';
  if (dayStart.getTime() >= weekStart.getTime()) return 'Cette semaine';
  return 'Plus tôt';
}

const GLOBAL_STYLES = `
  @import url('https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,400;9..144,500;9..144,600;9..144,700;9..144,800;9..144,900&family=JetBrains+Mono:wght@400;500;600;700&family=Inter:wght@400;500;600;700&display=swap');
  .ws-display { font-family: 'Fraunces', serif; font-optical-sizing: auto; letter-spacing: -0.02em; }
  .ws-mono { font-family: 'JetBrains Mono', monospace; }
  .ws-pill { display: inline-flex; align-items: center; gap: 6px; padding: 4px 10px; border-radius: 100px; font-size: 11px; font-weight: 600; letter-spacing: 0.02em; }
  .ws-icon-btn { width: 34px; height: 34px; border-radius: 9px; background: ${C.indigoSoft}; color: ${C.indigoDeep}; display: flex; align-items: center; justify-content: center; cursor: pointer; border: none; transition: all 0.2s ease; flex-shrink: 0; }
  .ws-icon-btn:hover { background: ${C.indigoDeep}; color: ${C.cream}; }
  .ws-icon-btn.ghost { background: transparent; color: ${C.inkSoft}; }
  .ws-icon-btn.ghost:hover { background: ${C.creamDeep}; color: ${C.indigoDeep}; }
  .ws-icon-btn.danger { background: ${C.redSoft}; color: ${C.redDeep}; }
  .ws-icon-btn.danger:hover { background: ${C.red}; color: ${C.cream}; }
  .ws-grain::before { content: ''; position: absolute; inset: 0; background-image: url("data:image/svg+xml,%3Csvg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='3'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='0.4'/%3E%3C/svg%3E"); opacity: 0.06; pointer-events: none; mix-blend-mode: overlay; }
  .ws-live-dot { width: 8px; height: 8px; border-radius: 50%; background: ${C.sage}; position: relative; flex-shrink: 0; }
  .ws-live-dot::after { content: ''; position: absolute; inset: -4px; border-radius: 50%; background: ${C.sage}; opacity: 0.4; animation: wsPulse 1.8s ease-in-out infinite; }
  @keyframes wsPulse { 0%,100% { transform: scale(1); opacity: 0.5; } 50% { transform: scale(1.6); opacity: 0; } }
  @keyframes wsSlideIn { from { opacity: 0; transform: translateY(20px); } to { opacity: 1; transform: translateY(0); } }
  .ws-stagger > * { animation: wsSlideIn 0.4s ease-out backwards; }
  .ws-stagger > *:nth-child(1){animation-delay:.05s}.ws-stagger > *:nth-child(2){animation-delay:.08s}.ws-stagger > *:nth-child(3){animation-delay:.11s}.ws-stagger > *:nth-child(4){animation-delay:.14s}.ws-stagger > *:nth-child(5){animation-delay:.17s}.ws-stagger > *:nth-child(6){animation-delay:.20s}.ws-stagger > *:nth-child(n+7){animation-delay:.23s}
  .ws-card-lift { transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1); }
  .ws-card-lift:hover { transform: translateY(-2px); }
  .ws-row { transition: all 0.2s ease; position: relative; }
  .ws-row:hover { transform: translateX(2px); box-shadow: 0 8px 24px -8px rgba(67,56,202,0.15); }
  .ws-row:hover .ws-quick { opacity: 1; transform: translateX(0); }
  .ws-quick { opacity: 0; transform: translateX(8px); transition: all 0.2s ease; }
  .ws-row.selected { background: ${C.indigoSoft} !important; border-color: ${C.indigo} !important; box-shadow: 0 0 0 1px ${C.indigo}, 0 8px 24px -8px ${C.indigo}40 !important; }
  @keyframes wsUrgent { 0%,100% { box-shadow: 0 0 0 0 ${C.red}80; } 50% { box-shadow: 0 0 0 6px ${C.red}00; } }
  .ws-urgent { animation: wsUrgent 2s ease-in-out infinite; }
  @keyframes wsRotate { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }
  .ws-rotate { animation: wsRotate 30s linear infinite; }
  @keyframes wsFloat { 0%,100% { transform: translateY(0) rotate(0deg); opacity: 0.5; } 50% { transform: translateY(-8px) rotate(180deg); opacity: 1; } }
  .ws-float { animation: wsFloat 4s ease-in-out infinite; }
  @keyframes wsShimmer { 0% { background-position: -200% center; } 100% { background-position: 200% center; } }
  .ws-shimmer { background: linear-gradient(90deg, ${C.indigoLight}, ${C.gold}, ${C.indigoLight}, ${C.gold}, ${C.indigoLight}); background-size: 200% auto; background-clip: text; -webkit-background-clip: text; -webkit-text-fill-color: transparent; animation: wsShimmer 4s linear infinite; }
  @keyframes wsSlideRight { from { transform: translateX(20px); opacity: 0; } to { transform: translateX(0); opacity: 1; } }
  .ws-slide-right { animation: wsSlideRight 0.3s ease-out; }
  .ws-thin::-webkit-scrollbar { width: 6px; }
  .ws-thin::-webkit-scrollbar-thumb { background: rgba(10,42,32,0.15); border-radius: 100px; }
  @keyframes wsScale { from { transform: scale(0.95); opacity: 0; } to { transform: scale(1); opacity: 1; } }
  .ws-scale-in { animation: wsScale 0.3s cubic-bezier(0.4, 0, 0.2, 1); }
  /* Detail panel drawer overlay (visible only when collapsed below 1280px) */
  .ws-detail-overlay { display: none; position: fixed; inset: 0; background: rgba(4,42,31,0.55); backdrop-filter: blur(4px); z-index: 99; opacity: 0; pointer-events: none; transition: opacity 0.2s ease; }
  @media (max-width: 1279px) {
    .ws-detail-overlay { display: block; }
    .ws-detail-overlay.open { opacity: 1; pointer-events: auto; }
  }

  /* ─── ≥1280 px : layout 2 colonnes (main + side panel) ───────────────── */
  /* ─── ≤1279 px : panneau détail = drawer côté droit (420 px) ─────────── */
  @media (max-width: 1279px) {
    .ws-main { max-width: none !important; }
    .ws-detail {
      position: fixed !important;
      top: 0 !important; right: 0 !important;
      height: 100vh !important; max-height: 100vh !important;
      width: 420px !important; max-width: 92vw !important;
      border-radius: 18px 0 0 18px !important;
      z-index: 100 !important;
      box-shadow: -20px 0 60px -20px rgba(0,0,0,0.5) !important;
      transform: translateX(100%);
      transition: transform 0.28s cubic-bezier(0.4,0,0.2,1) !important;
    }
    .ws-detail.open { transform: translateX(0); }
  }

  /* ─── ≤1024 px : tablet ─────────────────────────────────────────────── */
  @media (max-width: 1024px) {
    .ws-grid-4 { grid-template-columns: repeat(2, 1fr) !important; }
    .ws-shell { padding: 14px !important; }
    .ws-hero-pad { padding: 22px 20px !important; }
    .ws-hero-title { font-size: 30px !important; }
  }

  /* ─── ≤768 px : mobile ──────────────────────────────────────────────── */
  @media (max-width: 768px) {
    .ws-hide-mobile { display: none !important; }
    .ws-grid-4 { grid-template-columns: 1fr 1fr !important; gap: 8px !important; }
    .ws-grid-4 > * { padding: 12px !important; }
    .ws-grid-4 .ws-display.ws-mono { font-size: 22px !important; }
    .ws-hero-title { font-size: 24px !important; }
    .ws-hero-pad { padding: 18px 14px !important; border-radius: 16px !important; }
    .ws-shell { padding: 8px !important; gap: 8px !important; }
    .ws-row-mobile { padding: 12px !important; gap: 10px !important; }
    .ws-row-mobile .ws-quick { opacity: 1 !important; transform: none !important; flex-direction: column !important; gap: 4px !important; }
    .ws-row-mobile .ws-quick .ws-icon-btn { width: 28px !important; height: 28px !important; }
    .ws-detail { width: 100vw !important; max-width: 100vw !important; border-radius: 0 !important; }
    .ws-filters-row { flex-direction: column !important; align-items: stretch !important; }
    .ws-filters-row > * { width: 100% !important; }
    .ws-hero-actions { width: 100% !important; }
    .ws-hero-actions button { flex: 1 1 calc(50% - 4px) !important; min-width: 0 !important; justify-content: center !important; }
  }

  /* ─── ≤480 px : ultra mobile ────────────────────────────────────────── */
  @media (max-width: 480px) {
    .ws-grid-4 { grid-template-columns: 1fr !important; }
    .ws-hero-title { font-size: 22px !important; }
    .ws-hero-pad { padding: 14px 12px !important; }
    .ws-hero-actions button { font-size: 12px !important; padding: 10px 12px !important; }
    .ws-row-mobile { padding: 10px !important; }
    .ws-row-mobile h4 { font-size: 13px !important; }
    .ws-pill { font-size: 9px !important; padding: 3px 7px !important; }
  }
`;

export default function WorkspacePage() {
  const { formatLocal: formatMoney } = useCurrency();
  const [items, setItems] = useState<Action[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [activeTab, setActiveTab] = useState<TypeKey | 'all'>('all');
  const [activeStatus, setActiveStatus] = useState<StatusKey | 'all'>('all');
  const [activeAgent, setActiveAgent] = useState<AgentKey | 'all'>('all');
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [checkedIds, setCheckedIds] = useState<Set<string>>(new Set());
  const [search, setSearch] = useState('');

  const load = async (silent = false) => {
    if (silent) setRefreshing(true); else setLoading(true);
    try {
      const r = await api.get('/marketplace/work-items?limit=100');
      const raw: RawWorkItem[] = Array.isArray(r.data) ? r.data : [];
      const now = Date.now();
      const mapped: Action[] = raw.map(w => {
        const type = mapType(w.type);
        const ms = tsToMs(w.createdAt);
        const data = w.data ?? {};
        const valueRaw = (data.amount ?? data.total ?? data.value ?? data.price) as number | undefined;
        const value = typeof valueRaw === 'number' ? valueRaw : undefined;
        const ageHours = (now - ms) / 3_600_000;
        const status = mapStatus(w.status);
        return {
          id: w.id,
          type,
          title: w.title || `${TYPES[type].label} sans titre`,
          sub: w.summary || '',
          agent: mapAgent(w.agentName, type),
          date: formatActionDate(ms),
          rawDate: ms,
          status,
          priority: derivePriority(type, value, ageHours),
          client: (data.clientName ?? data.client ?? data.contactName) as string | undefined,
          value,
          duration: data.duration as string | undefined,
          unread: status === 'pending' && ageHours < 24,
          raw: data,
        };
      });
      mapped.sort((a, b) => b.rawDate - a.rawDate);
      setItems(mapped);
    } catch {
      setItems([]);
    } finally {
      setLoading(false); setRefreshing(false);
    }
  };

  useEffect(() => { load(); }, []);

  const filtered = useMemo(() => items.filter(a => {
    if (activeTab !== 'all' && a.type !== activeTab) return false;
    if (activeStatus !== 'all' && a.status !== activeStatus) return false;
    if (activeAgent !== 'all' && a.agent !== activeAgent) return false;
    if (search.trim()) {
      const s = search.toLowerCase();
      if (!(a.title.toLowerCase().includes(s) || a.sub.toLowerCase().includes(s) || (a.client || '').toLowerCase().includes(s))) return false;
    }
    return true;
  }), [items, activeTab, activeStatus, activeAgent, search]);

  const grouped = useMemo(() => {
    const order = ["Aujourd'hui", 'Hier', 'Cette semaine', 'Plus tôt'];
    const map = new Map<string, Action[]>();
    for (const a of filtered) {
      const k = groupKey(a.rawDate);
      if (!map.has(k)) map.set(k, []);
      map.get(k)!.push(a);
    }
    return order.filter(k => map.has(k)).map(k => [k, map.get(k)!] as const);
  }, [filtered]);

  const stats = useMemo(() => {
    const total = items.length;
    const pendingCount = items.filter(i => i.status === 'pending').length;
    const urgent = items.filter(i => i.priority === 'urgent').length;
    const totalValue = items.filter(i => i.type === 'devis').reduce((s, i) => s + (i.value || 0), 0);
    const decided = items.filter(i => i.status === 'approved' || i.status === 'rejected');
    const approvedRate = decided.length > 0 ? Math.round((decided.filter(i => i.status === 'approved').length / decided.length) * 100) : 0;
    return { total, pendingCount, urgent, totalValue, approvedRate };
  }, [items]);

  const counts = useMemo(() => {
    const c: Record<TypeKey | 'all', number> = { all: items.length, devis: 0, rdv: 0, client: 0, facture: 0, email: 0, task: 0 };
    for (const i of items) c[i.type] = (c[i.type] || 0) + 1;
    return c;
  }, [items]);

  const agentCounts = useMemo(() => {
    const c: Partial<Record<AgentKey, number>> = {};
    const since = Date.now() - 24 * 3_600_000;
    for (const i of items) {
      if (i.rawDate < since) continue;
      c[i.agent] = (c[i.agent] || 0) + 1;
    }
    return c;
  }, [items]);

  const selected = useMemo(() => items.find(a => a.id === selectedId) || null, [items, selectedId]);

  const toggleCheck = (id: string) => {
    setCheckedIds(prev => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id); else next.add(id);
      return next;
    });
  };

  const approveOne = async (id: string) => {
    try { await api.post(`/marketplace/work-items/${id}/approve`); } catch { /* ignore */ }
    load(true);
  };
  const rejectOne = async (id: string) => {
    try { await api.post(`/marketplace/work-items/${id}/reject`); } catch { /* ignore */ }
    load(true);
  };
  const approveAll = async () => {
    const pending = items.filter(i => i.status === 'pending').map(i => i.id);
    if (pending.length === 0) return;
    if (!window.confirm(`Approuver ${pending.length} action(s) en attente ?`)) return;
    await Promise.all(pending.map(id => api.post(`/marketplace/work-items/${id}/approve`).catch(() => null)));
    load(true);
  };

  return (
    <div className="ws-shell" style={{ padding: 20, display: 'flex', gap: 16, alignItems: 'flex-start', minHeight: '100vh', background: C.greenDeep, fontFamily: "'Inter', sans-serif" }}>
      <style>{GLOBAL_STYLES}</style>

      <div className="ws-main" style={{ flex: 1, minWidth: 0, maxWidth: selected ? 'calc(100% - 396px)' : '100%', display: 'flex', flexDirection: 'column', gap: 14 }}>
        <HeroSection
          totalCount={stats.total}
          pendingCount={stats.pendingCount}
          agentCounts={agentCounts}
          onApproveAll={approveAll}
          onRefresh={() => load(true)}
          refreshing={refreshing}
        />

        <StatsCards stats={stats} formatMoney={formatMoney} />

        <FiltersBar
          activeTab={activeTab} setActiveTab={setActiveTab}
          activeStatus={activeStatus} setActiveStatus={setActiveStatus}
          activeAgent={activeAgent} setActiveAgent={setActiveAgent}
          search={search} setSearch={setSearch}
          counts={counts}
        />

        <BulkActionsBar count={checkedIds.size} onClose={() => setCheckedIds(new Set())} />

        {loading ? (
          <div style={{ background: C.cream, borderRadius: 18, padding: 60, textAlign: 'center' }}>
            <RefreshCw size={28} color={C.indigo} className="ws-rotate" style={{ marginBottom: 12 }} />
            <div className="ws-display" style={{ fontSize: 16, color: C.ink }}>Chargement…</div>
          </div>
        ) : grouped.length === 0 ? (
          <div style={{ background: C.cream, borderRadius: 18, padding: 60, textAlign: 'center', border: '1px dashed rgba(10,42,32,0.15)' }}>
            <Inbox size={48} color={C.inkLight} style={{ marginBottom: 12 }} />
            <h3 className="ws-display" style={{ fontSize: 18, color: C.ink, margin: '0 0 6px' }}>
              {items.length === 0 ? 'Aucune action générée pour l\'instant' : 'Aucune action ne correspond aux filtres'}
            </h3>
            <p style={{ fontSize: 13, color: C.inkSoft, margin: 0 }}>
              {items.length === 0 ? 'Vos agents IA n\'ont rien produit récemment.' : 'Essayez d\'ajuster vos filtres.'}
            </p>
          </div>
        ) : grouped.map(([day, list]) => (
          <div key={day}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '6px 4px 10px' }}>
              <span className="ws-display" style={{ fontSize: 14, fontWeight: 700, color: C.cream, letterSpacing: '-0.01em' }}>{day}</span>
              <span className="ws-pill" style={{ background: 'rgba(255,250,240,0.08)', color: C.onGreenSoft, fontWeight: 700, fontSize: 10, border: '1px solid rgba(255,250,240,0.1)' }}>
                {list.length} action{list.length > 1 ? 's' : ''}
              </span>
              <div style={{ flex: 1, height: 1, background: 'rgba(255,250,240,0.08)' }} />
            </div>
            <div className="ws-stagger" style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
              {list.map(a => (
                <ActionRow
                  key={a.id}
                  action={a}
                  selected={selectedId === a.id}
                  isChecked={checkedIds.has(a.id)}
                  onSelect={setSelectedId}
                  onCheckChange={toggleCheck}
                  onApprove={() => approveOne(a.id)}
                  onReject={() => rejectOne(a.id)}
                  formatMoney={formatMoney}
                />
              ))}
            </div>
          </div>
        ))}
      </div>

      {/* Backdrop visible only when drawer mode kicks in (≤1279px) */}
      <div
        className={`ws-detail-overlay ${selected ? 'open' : ''}`}
        onClick={() => setSelectedId(null)}
        aria-hidden="true"
      />

      {selected && (
        <DetailPanel
          action={selected}
          onClose={() => setSelectedId(null)}
          onApprove={() => approveOne(selected.id)}
          onReject={() => rejectOne(selected.id)}
          formatMoney={formatMoney}
          isOpen
        />
      )}
    </div>
  );
}

interface HeroProps { totalCount: number; pendingCount: number; agentCounts: Partial<Record<AgentKey, number>>; onApproveAll: () => void; onRefresh: () => void; refreshing: boolean }
function HeroSection({ totalCount, pendingCount, agentCounts, onApproveAll, onRefresh, refreshing }: HeroProps) {
  const topAgents = (Object.entries(agentCounts) as [AgentKey, number][])
    .sort((a, b) => b[1] - a[1]).slice(0, 4);
  return (
    <div className="ws-hero-pad" style={{ position: 'relative', background: `linear-gradient(135deg, ${C.indigoDark} 0%, ${C.indigoDeep} 100%)`, borderRadius: 22, padding: '28px 32px', overflow: 'hidden', border: `1px solid ${C.indigo}40`, boxShadow: '0 20px 50px -20px rgba(67,56,202,0.4)' }}>
      <div className="ws-grain" />
      <div className="ws-rotate" style={{ position: 'absolute', top: -80, right: -80, width: 320, height: 320, borderRadius: '50%', border: `1px dashed ${C.gold}30`, pointerEvents: 'none' }} />
      <div className="ws-rotate" style={{ position: 'absolute', top: -40, right: -40, width: 240, height: 240, borderRadius: '50%', border: `1px dashed ${C.gold}20`, pointerEvents: 'none', animationDirection: 'reverse', animationDuration: '40s' }} />
      <div className="ws-float" style={{ position: 'absolute', top: 40, right: 120, opacity: 0.6 }}><Sparkles size={18} color={C.gold} /></div>
      <div className="ws-float" style={{ position: 'absolute', top: 100, right: 280, opacity: 0.5, animationDelay: '1s' }}><Sparkles size={14} color={C.indigoLight} /></div>

      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', position: 'relative', zIndex: 2, gap: 24, flexWrap: 'wrap' }}>
        <div style={{ flex: 1, minWidth: 280 }}>
          <div className="ws-pill" style={{ background: 'rgba(212,160,23,0.15)', color: C.goldLight, border: `1px solid ${C.gold}40`, fontWeight: 700, marginBottom: 12 }}>
            <Inbox size={11} /> INBOX IA · {pendingCount} EN ATTENTE DE REVIEW
          </div>
          <h1 className="ws-display ws-hero-title" style={{ fontSize: 36, fontWeight: 800, color: C.cream, margin: 0, letterSpacing: '-0.02em', lineHeight: 1.1 }}>
            Espace de <em className="ws-shimmer" style={{ fontStyle: 'italic', fontWeight: 500 }}>travail</em>
          </h1>
          <p style={{ fontSize: 14, color: C.indigoLight, margin: '8px 0 16px', lineHeight: 1.5 }}>
            <strong style={{ color: C.cream }}>{totalCount} actions</strong> générées par vos agents IA.{' '}
            <strong style={{ color: C.gold }}>{pendingCount} en attente</strong> de votre validation.
          </p>
          <div className="ws-hero-actions" style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
            <button onClick={onApproveAll} disabled={pendingCount === 0} style={{
              background: pendingCount === 0 ? 'rgba(255,250,240,0.15)' : `linear-gradient(135deg, ${C.gold}, ${C.goldDeep})`,
              color: pendingCount === 0 ? C.indigoLight : C.greenInk, border: 'none',
              padding: '11px 20px', borderRadius: 12, fontWeight: 700, fontSize: 13,
              cursor: pendingCount === 0 ? 'not-allowed' : 'pointer', fontFamily: 'inherit',
              display: 'inline-flex', alignItems: 'center', gap: 8,
              boxShadow: pendingCount === 0 ? 'none' : `0 8px 24px -8px ${C.gold}`,
            }}>
              <CheckCircle2 size={14} /> Tout valider
            </button>
            <button onClick={onRefresh} style={{ background: 'rgba(255,250,240,0.08)', color: C.cream, border: '1px solid rgba(255,250,240,0.15)', padding: '11px 18px', borderRadius: 12, fontWeight: 600, fontSize: 13, cursor: 'pointer', fontFamily: 'inherit', display: 'inline-flex', alignItems: 'center', gap: 7 }}>
              <RefreshCw size={13} className={refreshing ? 'ws-rotate' : ''} /> Actualiser
            </button>
            <button style={{ background: 'rgba(255,250,240,0.08)', color: C.cream, border: '1px solid rgba(255,250,240,0.15)', padding: '11px 18px', borderRadius: 12, fontWeight: 600, fontSize: 13, cursor: 'pointer', fontFamily: 'inherit', display: 'inline-flex', alignItems: 'center', gap: 7 }}>
              <SlidersHorizontal size={13} /> Filtres avancés
            </button>
          </div>
        </div>

        <div className="ws-hide-mobile" style={{ background: 'rgba(255,250,240,0.06)', border: `1px solid ${C.indigo}50`, borderRadius: 16, padding: 18, minWidth: 240, backdropFilter: 'blur(20px)' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 12 }}>
            <div className="ws-live-dot" />
            <span style={{ fontSize: 10, fontWeight: 800, color: C.gold, letterSpacing: '0.1em' }}>AGENTS · DERNIÈRES 24H</span>
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
            {topAgents.length === 0 ? (
              <div style={{ fontSize: 12, color: C.indigoLight }}>Pas d'activité récente.</div>
            ) : topAgents.map(([k, n]) => {
              const a = AGENTS_INFO[k];
              return (
                <div key={k} style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 12 }}>
                  <span style={{ fontSize: 14 }}>{a.emoji}</span>
                  <span style={{ color: C.cream, flex: 1, fontWeight: 500 }}>{a.name.replace('Agent ', '')}</span>
                  <span className="ws-mono" style={{ background: `${a.color}25`, color: a.color, fontWeight: 700, padding: '2px 7px', borderRadius: 100, fontSize: 10 }}>+{n}</span>
                </div>
              );
            })}
          </div>
        </div>
      </div>
    </div>
  );
}

interface StatsProps { stats: { total: number; pendingCount: number; urgent: number; totalValue: number; approvedRate: number }; formatMoney: (v: number) => string }
function StatsCards({ stats, formatMoney }: StatsProps) {
  const cards: { label: string; value: string; sub?: string; change: string; trend: 'up' | 'flat' | 'down'; icon: typeof Sparkles; main: string; deep: string; soft: string }[] = [
    { label: 'Actions générées', value: String(stats.total), change: 'cumul global', trend: 'up', icon: Sparkles, main: C.indigo, deep: C.indigoDeep, soft: C.indigoSoft },
    { label: 'En attente review', value: String(stats.pendingCount), change: stats.urgent > 0 ? `${stats.urgent} urgentes` : 'à jour', trend: stats.urgent > 0 ? 'flat' : 'down', icon: Clock, main: C.gold, deep: C.goldDeep, soft: C.goldSoft },
    { label: 'Valeur totale devis', value: formatMoney(stats.totalValue), change: 'tous devis', trend: 'up', icon: DollarSign, main: C.sage, deep: C.sageDeep, soft: C.sageSoft },
    { label: "Taux d'approbation", value: `${stats.approvedRate}%`, change: stats.approvedRate >= 70 ? 'Élevé' : 'À surveiller', trend: stats.approvedRate >= 70 ? 'up' : 'down', icon: BadgeCheck, main: C.terracotta, deep: C.terraDeep, soft: C.terraSoft },
  ];
  return (
    <div className="ws-grid-4 ws-stagger" style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 12 }}>
      {cards.map((s, i) => {
        const Icon = s.icon;
        const TrendIcon = s.trend === 'up' ? ArrowUpRight : s.trend === 'down' ? ArrowDownRight : Minus;
        return (
          <div key={i} className="ws-card-lift" style={{ background: C.cream, borderRadius: 16, padding: 18, border: '1px solid rgba(10,42,32,0.06)', cursor: 'pointer', position: 'relative', overflow: 'hidden' }}>
            <div style={{ position: 'absolute', top: 0, left: 0, right: 0, height: 3, background: `linear-gradient(90deg, ${s.main}, ${s.deep})` }} />
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 10 }}>
              <div style={{ width: 40, height: 40, borderRadius: 11, background: s.soft, color: s.deep, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                <Icon size={20} />
              </div>
              <span className="ws-pill" style={{ background: s.trend === 'up' ? C.sageSoft : C.goldSoft, color: s.trend === 'up' ? C.sageDark : C.goldDark, fontWeight: 700, fontSize: 10 }}>
                <TrendIcon size={9} /> {s.change}
              </span>
            </div>
            <div className="ws-display ws-mono" style={{ fontSize: 30, fontWeight: 800, color: C.ink, lineHeight: 1, letterSpacing: '-0.02em' }}>{s.value}</div>
            <div style={{ fontSize: 12, fontWeight: 700, color: C.ink, marginTop: 6 }}>{s.label}</div>
          </div>
        );
      })}
    </div>
  );
}

interface FiltersProps {
  activeTab: TypeKey | 'all'; setActiveTab: (v: TypeKey | 'all') => void;
  activeStatus: StatusKey | 'all'; setActiveStatus: (v: StatusKey | 'all') => void;
  activeAgent: AgentKey | 'all'; setActiveAgent: (v: AgentKey | 'all') => void;
  search: string; setSearch: (v: string) => void;
  counts: Record<TypeKey | 'all', number>;
}
function FiltersBar({ activeTab, setActiveTab, activeStatus, setActiveStatus, activeAgent, setActiveAgent, search, setSearch, counts }: FiltersProps) {
  const tabs: { id: TypeKey | 'all'; label: string; color: string }[] = [
    { id: 'all',     label: 'Tout',         color: C.indigo },
    { id: 'devis',   label: 'Devis',        color: C.indigo },
    { id: 'rdv',     label: 'Rendez-vous',  color: C.blue },
    { id: 'client',  label: 'Clients',      color: C.sage },
    { id: 'facture', label: 'Factures',     color: C.gold },
    { id: 'email',   label: 'Emails',       color: C.purple },
    { id: 'task',    label: 'Tâches',       color: C.terracotta },
  ];
  return (
    <div style={{ background: C.cream, borderRadius: 14, padding: 12, border: '1px solid rgba(10,42,32,0.06)', display: 'flex', flexDirection: 'column', gap: 10 }}>
      <div style={{ display: 'flex', gap: 6, alignItems: 'center', flexWrap: 'nowrap', overflowX: 'auto' }}>
        {tabs.map(t => {
          const active = activeTab === t.id;
          return (
            <button key={t.id} onClick={() => setActiveTab(t.id)} style={{
              background: active ? `linear-gradient(135deg, ${t.color}, ${t.color}cc)` : 'transparent',
              color: active ? C.cream : C.inkSoft,
              padding: '8px 14px', borderRadius: 100, fontSize: 12, fontWeight: 700, cursor: 'pointer',
              border: active ? 'none' : '1px solid rgba(10,42,32,0.1)', fontFamily: 'inherit',
              display: 'inline-flex', alignItems: 'center', gap: 6,
              boxShadow: active ? `0 6px 14px -4px ${t.color}` : 'none', flexShrink: 0,
              transition: 'all 0.2s ease',
            }}>
              {t.label}
              <span className="ws-mono" style={{ background: active ? 'rgba(255,250,240,0.25)' : C.creamDeep, color: active ? C.cream : C.inkSoft, padding: '1px 6px', borderRadius: 6, fontSize: 10 }}>
                {counts[t.id] ?? 0}
              </span>
            </button>
          );
        })}
      </div>
      <div className="ws-filters-row" style={{ display: 'flex', gap: 8, alignItems: 'center', flexWrap: 'wrap' }}>
        <div style={{ flex: 1, minWidth: 200, background: C.creamDeep, borderRadius: 10, padding: '7px 12px', display: 'flex', alignItems: 'center', gap: 8 }}>
          <Search size={13} color={C.inkSoft} />
          <input value={search} onChange={e => setSearch(e.target.value)} placeholder="Rechercher par client, montant, agent…" style={{ flex: 1, border: 'none', outline: 'none', background: 'transparent', fontSize: 12, color: C.ink, fontFamily: 'inherit', minWidth: 0 }} />
        </div>
        <select value={activeStatus} onChange={e => setActiveStatus(e.target.value as StatusKey | 'all')} style={{ background: C.creamDeep, color: C.ink, border: 'none', borderRadius: 10, padding: '8px 12px', fontSize: 12, fontWeight: 600, fontFamily: 'inherit', cursor: 'pointer' }}>
          <option value="all">Tous statuts</option>
          <option value="pending">En attente</option>
          <option value="approved">Approuvés</option>
          <option value="rejected">Rejetés</option>
          <option value="completed">Complétés</option>
        </select>
        <select value={activeAgent} onChange={e => setActiveAgent(e.target.value as AgentKey | 'all')} style={{ background: C.creamDeep, color: C.ink, border: 'none', borderRadius: 10, padding: '8px 12px', fontSize: 12, fontWeight: 600, fontFamily: 'inherit', cursor: 'pointer' }}>
          <option value="all">Tous les agents</option>
          {(Object.entries(AGENTS_INFO) as [AgentKey, typeof AGENTS_INFO[AgentKey]][]).map(([k, v]) => (
            <option key={k} value={k}>{v.emoji} {v.name}</option>
          ))}
        </select>
        <button style={{ background: 'transparent', color: C.inkSoft, border: '1px solid rgba(10,42,32,0.1)', padding: '8px 12px', borderRadius: 10, fontSize: 12, fontWeight: 600, cursor: 'pointer', fontFamily: 'inherit', display: 'inline-flex', alignItems: 'center', gap: 5 }}>
          <ChevronsUpDown size={12} /> Date ↓
        </button>
      </div>
    </div>
  );
}

interface RowProps { action: Action; selected: boolean; isChecked: boolean; onSelect: (id: string) => void; onCheckChange: (id: string) => void; onApprove: () => void; onReject: () => void; formatMoney: (v: number) => string }
function ActionRow({ action, selected, isChecked, onSelect, onCheckChange, onApprove, onReject, formatMoney }: RowProps) {
  const type = TYPES[action.type];
  const TypeIcon = type.icon;
  const status = STATUS_CONFIG[action.status];
  const priority = PRIORITY_CONFIG[action.priority];
  const agent = AGENTS_INFO[action.agent];
  return (
    <div onClick={() => onSelect(action.id)} className={`ws-row ws-row-mobile ws-card-lift ${selected ? 'selected' : ''}`} style={{
      background: action.unread ? `${type.bg}30` : C.cream,
      borderRadius: 14, padding: 14, cursor: 'pointer',
      border: action.unread ? `1.5px solid ${type.color}30` : '1px solid rgba(10,42,32,0.06)',
      display: 'flex', gap: 12, alignItems: 'flex-start',
      borderLeft: action.priority === 'urgent' ? `4px solid ${C.red}` : (action.unread ? `4px solid ${type.color}` : '1px solid rgba(10,42,32,0.06)'),
    }}>
      <div onClick={e => { e.stopPropagation(); onCheckChange(action.id); }} style={{
        width: 18, height: 18, borderRadius: 5, border: `2px solid ${isChecked ? C.indigo : C.inkLight}`,
        background: isChecked ? C.indigo : 'transparent', display: 'flex', alignItems: 'center', justifyContent: 'center',
        flexShrink: 0, marginTop: 4, transition: 'all 0.15s ease',
      }}>
        {isChecked && <Check size={12} color={C.cream} strokeWidth={3} />}
      </div>
      <div style={{ width: 44, height: 44, borderRadius: 12, background: `linear-gradient(135deg, ${type.color}, ${type.deep})`, color: C.cream, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, boxShadow: `0 6px 14px -4px ${type.color}` }}>
        <TypeIcon size={20} />
      </div>
      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 3, flexWrap: 'wrap' }}>
          <h4 className="ws-display" style={{ fontSize: 14, fontWeight: 700, color: C.ink, margin: 0, letterSpacing: '-0.01em' }}>{action.title}</h4>
          {action.unread && <div style={{ width: 8, height: 8, borderRadius: '50%', background: type.color, boxShadow: `0 0 0 2px ${type.bg}` }} />}
          <span className="ws-pill" style={{ background: type.bg, color: type.deep, fontSize: 9, fontWeight: 700 }}><TypeIcon size={9} /> {type.label}</span>
          <span className="ws-pill" style={{ background: status.bg, color: status.deep, fontSize: 9, fontWeight: 700 }}>● {status.label}</span>
          {action.priority === 'urgent' && (
            <span className="ws-pill ws-urgent" style={{ background: C.red, color: C.cream, fontSize: 9, fontWeight: 800 }}>{priority.icon} {priority.label}</span>
          )}
        </div>
        {action.sub && <div style={{ fontSize: 12, color: C.inkSoft, marginBottom: 6 }}>{action.sub}</div>}
        <div style={{ display: 'flex', alignItems: 'center', gap: 12, fontSize: 11, color: C.inkLight, flexWrap: 'wrap' }}>
          <span style={{ display: 'inline-flex', alignItems: 'center', gap: 5 }}>
            <span style={{ width: 18, height: 18, borderRadius: 5, background: `linear-gradient(135deg, ${agent.color}, ${agent.color}cc)`, color: C.cream, display: 'inline-flex', alignItems: 'center', justifyContent: 'center', fontSize: 10 }}>{agent.emoji}</span>
            <span style={{ fontWeight: 600, color: C.inkSoft }}>{agent.name}</span>
          </span>
          <span>·</span>
          <span style={{ display: 'inline-flex', alignItems: 'center', gap: 4 }}><Clock size={10} /> {action.date}</span>
          {action.client && (<><span>·</span><span style={{ display: 'inline-flex', alignItems: 'center', gap: 4 }}><User size={10} /> {action.client}</span></>)}
          {typeof action.value === 'number' && (<><span>·</span><span className="ws-mono" style={{ color: C.gold, fontWeight: 700 }}>{formatMoney(action.value)}</span></>)}
        </div>
      </div>
      <div className="ws-quick" style={{ display: 'flex', gap: 4, flexShrink: 0 }}>
        {action.status === 'pending' && (<>
          <button onClick={e => { e.stopPropagation(); onApprove(); }} className="ws-icon-btn" style={{ background: C.sageSoft, color: C.sageDark }} title="Approuver"><Check size={14} /></button>
          <button onClick={e => { e.stopPropagation(); onReject(); }} className="ws-icon-btn danger" title="Rejeter"><X size={14} /></button>
        </>)}
        <button onClick={e => e.stopPropagation()} className="ws-icon-btn ghost"><MoreVertical size={14} /></button>
      </div>
    </div>
  );
}

interface DetailProps { action: Action; onClose: () => void; onApprove: () => void; onReject: () => void; formatMoney: (v: number) => string; isOpen?: boolean }
function DetailPanel({ action, onClose, onApprove, onReject, formatMoney, isOpen }: DetailProps) {
  const type = TYPES[action.type];
  const TypeIcon = type.icon;
  const status = STATUS_CONFIG[action.status];
  const agent = AGENTS_INFO[action.agent];
  return (
    <div className={`ws-detail ws-slide-right ${isOpen ? 'open' : ''}`} style={{ width: 380, flexShrink: 0, background: C.cream, borderRadius: 18, border: '1px solid rgba(10,42,32,0.08)', overflow: 'hidden', position: 'sticky', top: 90, maxHeight: 'calc(100vh - 110px)', display: 'flex', flexDirection: 'column' }}>
      <div style={{ background: `linear-gradient(135deg, ${type.color}, ${type.deep})`, padding: 20, color: C.cream, position: 'relative' }}>
        <div className="ws-grain" />
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 12 }}>
          <div style={{ width: 48, height: 48, borderRadius: 14, background: 'rgba(255,250,240,0.2)', backdropFilter: 'blur(20px)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            <TypeIcon size={24} color={C.cream} />
          </div>
          <button onClick={onClose} style={{ background: 'rgba(255,250,240,0.15)', border: 'none', borderRadius: 10, width: 32, height: 32, color: C.cream, cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            <X size={16} />
          </button>
        </div>
        <h3 className="ws-display" style={{ fontSize: 20, fontWeight: 800, margin: '0 0 6px', letterSpacing: '-0.02em', lineHeight: 1.2 }}>{action.title}</h3>
        {action.sub && <div style={{ fontSize: 12, opacity: 0.85 }}>{action.sub}</div>}
      </div>

      <div className="ws-thin" style={{ flex: 1, overflowY: 'auto', padding: 20 }}>
        <div style={{ padding: 12, background: status.bg, borderRadius: 12, marginBottom: 16, border: `1px solid ${status.color}30` }}>
          <div style={{ fontSize: 10, fontWeight: 700, color: status.deep, letterSpacing: '0.08em', marginBottom: 4 }}>STATUT</div>
          <div style={{ fontSize: 14, fontWeight: 700, color: status.deep, display: 'flex', alignItems: 'center', gap: 6 }}>
            <CheckCircle2 size={14} /> {status.label}
          </div>
        </div>

        <div style={{ marginBottom: 16 }}>
          <div style={{ fontSize: 10, fontWeight: 700, color: C.inkSoft, letterSpacing: '0.08em', marginBottom: 8 }}>GÉNÉRÉ PAR</div>
          <div style={{ background: C.creamDeep, borderRadius: 12, padding: 12, display: 'flex', alignItems: 'center', gap: 10 }}>
            <div style={{ width: 40, height: 40, borderRadius: 11, background: `linear-gradient(135deg, ${agent.color}, ${agent.color}cc)`, color: C.cream, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 18, boxShadow: `0 6px 12px -4px ${agent.color}` }}>{agent.emoji}</div>
            <div style={{ flex: 1, minWidth: 0 }}>
              <div style={{ fontSize: 13, fontWeight: 700, color: C.ink }}>{agent.name}</div>
              <div className="ws-mono" style={{ fontSize: 10, color: C.inkLight }}>{action.date}</div>
            </div>
          </div>
        </div>

        <div style={{ marginBottom: 16 }}>
          <div style={{ fontSize: 10, fontWeight: 700, color: C.inkSoft, letterSpacing: '0.08em', marginBottom: 8 }}>DÉTAILS</div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
            {action.client && (
              <div style={{ background: C.creamDeep, borderRadius: 10, padding: 10, display: 'flex', alignItems: 'center', gap: 8 }}>
                <User size={14} color={C.inkSoft} />
                <span style={{ fontSize: 11, color: C.inkSoft }}>Client</span>
                <span style={{ fontSize: 12, color: C.ink, fontWeight: 700, marginLeft: 'auto' }}>{action.client}</span>
              </div>
            )}
            {typeof action.value === 'number' && (
              <div style={{ background: C.goldSoft, borderRadius: 10, padding: 10, display: 'flex', alignItems: 'center', gap: 8, border: `1px solid ${C.gold}30` }}>
                <DollarSign size={14} color={C.goldDark} />
                <span style={{ fontSize: 11, color: C.goldDark, fontWeight: 600 }}>Montant</span>
                <span className="ws-mono" style={{ fontSize: 13, color: C.goldDark, fontWeight: 800, marginLeft: 'auto' }}>{formatMoney(action.value)}</span>
              </div>
            )}
            {action.duration && (
              <div style={{ background: C.creamDeep, borderRadius: 10, padding: 10, display: 'flex', alignItems: 'center', gap: 8 }}>
                <Clock size={14} color={C.inkSoft} />
                <span style={{ fontSize: 11, color: C.inkSoft }}>Durée</span>
                <span style={{ fontSize: 12, color: C.ink, fontWeight: 700, marginLeft: 'auto' }}>{action.duration}</span>
              </div>
            )}
            <div style={{ background: C.creamDeep, borderRadius: 10, padding: 10, display: 'flex', alignItems: 'center', gap: 8 }}>
              <Flame size={14} color={PRIORITY_CONFIG[action.priority].color} />
              <span style={{ fontSize: 11, color: C.inkSoft }}>Priorité</span>
              <span className="ws-pill" style={{ background: PRIORITY_CONFIG[action.priority].bg, color: PRIORITY_CONFIG[action.priority].color, marginLeft: 'auto', fontWeight: 700, fontSize: 10 }}>{PRIORITY_CONFIG[action.priority].label}</span>
            </div>
          </div>
        </div>

        <div style={{ marginBottom: 16 }}>
          <div style={{ fontSize: 10, fontWeight: 700, color: C.inkSoft, letterSpacing: '0.08em', marginBottom: 8 }}>POURQUOI L'IA A FAIT ÇA</div>
          <div style={{ background: `linear-gradient(135deg, ${C.indigoSoft}, ${C.purpleSoft})`, borderRadius: 12, padding: 12, border: `1px solid ${C.indigo}20` }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 6 }}>
              <Sparkles size={12} color={C.indigo} />
              <span style={{ fontSize: 10, fontWeight: 800, color: C.indigoDeep, letterSpacing: '0.08em' }}>ANALYSE IA</span>
            </div>
            <p style={{ fontSize: 12, color: C.ink, margin: 0, lineHeight: 1.5 }}>
              Cette action a été générée par <strong>{agent.name}</strong> à partir d'un signal entrant
              ({TYPES[action.type].label.toLowerCase()}). Vérifie les détails ci-dessus avant d'approuver.
            </p>
          </div>
        </div>

        <div>
          <div style={{ fontSize: 10, fontWeight: 700, color: C.inkSoft, letterSpacing: '0.08em', marginBottom: 8 }}>ACTIVITÉ</div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
            {[{ icon: Sparkles, text: 'Action créée par IA', time: action.date, color: C.indigo },
              { icon: Eye, text: 'Vue à l\'instant', time: 'maintenant', color: C.cyan }].map((a, i) => {
              const Icon = a.icon;
              return (
                <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '6px 10px', background: C.creamDeep, borderRadius: 8, fontSize: 11, color: C.inkSoft }}>
                  <Icon size={12} color={a.color} />
                  <span style={{ flex: 1 }}>{a.text}</span>
                  <span className="ws-mono" style={{ fontSize: 10, color: C.inkLight }}>{a.time}</span>
                </div>
              );
            })}
          </div>
        </div>
      </div>

      {action.status === 'pending' && (
        <div style={{ padding: 16, borderTop: `1px solid ${C.creamDeep}`, background: C.cream, display: 'flex', gap: 8 }}>
          <button onClick={onApprove} style={{ flex: 1, justifyContent: 'center', padding: '11px', background: `linear-gradient(135deg, ${C.sage}, ${C.sageDeep})`, color: C.greenInk, border: 'none', borderRadius: 10, fontWeight: 700, fontSize: 12, cursor: 'pointer', display: 'inline-flex', alignItems: 'center', gap: 6, fontFamily: 'inherit' }}>
            <Check size={14} /> Approuver
          </button>
          <button onClick={onReject} style={{ flex: 1, justifyContent: 'center', padding: '11px', background: C.cream, color: C.redDeep, border: `1.5px solid ${C.red}30`, borderRadius: 10, fontWeight: 600, fontSize: 12, cursor: 'pointer', display: 'inline-flex', alignItems: 'center', gap: 6, fontFamily: 'inherit' }}>
            <X size={14} /> Rejeter
          </button>
          <button className="ws-icon-btn ghost" style={{ width: 38, height: 38 }}><Edit3 size={15} /></button>
        </div>
      )}
    </div>
  );
}

function BulkActionsBar({ count, onClose }: { count: number; onClose: () => void }) {
  if (count === 0) return null;
  return (
    <div className="ws-scale-in" style={{ position: 'sticky', top: 90, zIndex: 5, background: `linear-gradient(135deg, ${C.indigoDark}, ${C.indigoDeep})`, borderRadius: 14, padding: '12px 18px', border: `1px solid ${C.gold}30`, display: 'flex', alignItems: 'center', gap: 12, boxShadow: `0 12px 30px -10px ${C.indigoDeep}`, flexWrap: 'wrap' }}>
      <div style={{ background: C.gold, color: C.greenInk, width: 32, height: 32, borderRadius: 9, display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 800, fontSize: 14, fontFamily: 'JetBrains Mono, monospace' }}>{count}</div>
      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{ fontSize: 13, fontWeight: 700, color: C.cream }}>{count} action{count > 1 ? 's' : ''} sélectionnée{count > 1 ? 's' : ''}</div>
        <div style={{ fontSize: 11, color: C.indigoLight }}>Choisissez une action groupée</div>
      </div>
      <button style={{ background: `linear-gradient(135deg, ${C.sage}, ${C.sageDeep})`, color: C.greenInk, border: 'none', padding: '9px 14px', borderRadius: 10, fontSize: 12, fontWeight: 700, cursor: 'pointer', fontFamily: 'inherit', display: 'inline-flex', alignItems: 'center', gap: 6 }}>
        <Check size={13} /> Approuver tout
      </button>
      <button style={{ background: 'rgba(255,250,240,0.1)', color: C.cream, border: '1px solid rgba(255,250,240,0.2)', padding: '9px 14px', borderRadius: 10, fontSize: 12, fontWeight: 600, cursor: 'pointer', fontFamily: 'inherit', display: 'inline-flex', alignItems: 'center', gap: 6 }}>
        <Archive size={13} /> Archiver
      </button>
      <button style={{ background: 'rgba(239,68,68,0.15)', color: '#FCA5A5', border: '1px solid rgba(239,68,68,0.3)', padding: '9px 14px', borderRadius: 10, fontSize: 12, fontWeight: 600, cursor: 'pointer', fontFamily: 'inherit', display: 'inline-flex', alignItems: 'center', gap: 6 }}>
        <X size={13} /> Rejeter
      </button>
      <button onClick={onClose} className="ws-icon-btn ghost" style={{ background: 'rgba(255,250,240,0.1)', color: C.cream, width: 32, height: 32 }}>
        <X size={14} />
      </button>
    </div>
  );
}
